version: '3'

volumes:
  data:

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres123"
    ports:
      - "15432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@postgres.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin123"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-network

  redis:
    image: redis
    command: redis-server --requirepass password
    ports:
      - "6379:6379"

networks:
  postgres-network:
    driver: bridge